### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by latetedemelon** [HiDeoo/Haku#128]
### Is your feature request related to a problem?

I'm not as familiar with NodeJS as I'd like, I'm not clear on how to get this running!

### Describe the solution you'd like

A build script; ideally docker containers with a docker compose.

**Comment by HiDeoo** [comment]
Thanks for the feedback. Indeed, I didn't have the bandwidth to setup proper instructions, or even a demo as this tool was mostly build for my own personal use.

To give a quick overview, the tool relies on various 3rd party services like Cloudinary, EmailJS, etc. [described in the README](https://github.com/HiDeoo/Haku/tree/1784c913d2bfc204e15549ccbfdc3e1fd0209ae3#architecture) as I didn't have the time to setup internal alternatives. Informations regarding these services must be specified in [a `.env` file](https://github.com/HiDeoo/Haku/blob/1784c913d2bfc204e15549ccbfdc3e1fd0209ae3/.env).

Regarding actual build, it's possible to look at [the `vercel-build` npm script](https://github.com/HiDeoo/Haku/blob/1784c913d2bfc204e15549ccbfdc3e1fd0209ae3/package.json#L22) used when deploying the tool on Vercel and does several things:

- Generate the Prisma (ORM) client (`prisma generate`)
- Apply pending migrations if any (`pnpm db:migrate`)
- Build the Next.js project and the custom service worker (`pnpm build`)

The development workflow is pretty much the same except you would use the `pnpm dev` command instead to start the application in development mode.

I have some todos regarding making this project more accessible altho I have no idea when I'll have the time to do so.
